SELECT * FROM ALL_TABLES;
select * from employee;
SELECT * FROM EMPLOYEES E
    JOIN ORDERS O ON O.SALESMAN_ID = E.EMPLOYEE_ID;
    
CREATE OR REPLACE VIEW TOTAL_VENTES_POUR_COMMANDE AS
SELECT 
    O.ORDER_ID,
    O.SALESMAN_ID,
    SUM(OI.UNIT_PRICE * OI.QUANTITY)AS "TOTAL_COMMANDE"
FROM ORDERS O 
    JOIN ORDER_ITEMS OI ON OI.ORDER_ID = O.ORDER_ID
    GROUP BY O.ORDER_ID, O.SALESMAN_ID;
    
SELECT O.ORDER_ID, O.SALESMAN_ID, TOTAL_COMMANDE, ORDER_DATE FROM TOTAL_VENTES_POUR_COMMANDE T
    JOIN ORDERS O ON O.ORDER_ID = T.ORDER_ID;
    
--    SELECT T.SALESMAN_ID, SUM(T.TOTAL_COMMANDE) FROM TOTAL_VENTES_POUR_COMMANDE T
--    JOIN ORDERS O ON O.ORDER_ID = T.ORDER_ID
--    GROUP BY T.SALESMAN_ID, YEAR();
    
    -- ORDERS + DATE + ANNEE
    CREATE OR REPLACE VIEW ORDER_DATE_ANNEE AS
    SELECT O.ORDER_ID, O.SALESMAN_ID, TOTAL_COMMANDE, TO_CHAR(ORDER_DATE, 'YYYY') AS "ANNEE" FROM TOTAL_VENTES_POUR_COMMANDE T
    JOIN ORDERS O ON O.ORDER_ID = T.ORDER_ID;
    
    -- MOYENNE DES VENTES CETTE ANEE
    
CREATE OR REPLACE VIEW MOYENNE_VENTES_ANNEE AS 
SELECT ANNEE, AVG(TOTAL_COMMANDE) AS "MOYENNE_VENTES_CETTE_ANNEE" FROM ORDER_DATE_ANNEE
GROUP BY ANNEE;


CREATE OR REPLACE VIEW MEILLEURE_VENTES_VENDEURS_ANNEE AS
SELECT SALESMAN_ID, annee, sum(total_commande) as "TOTAL_VENTES_CETTE_ANNEE"
FROM ORDER_DATE_ANNEE OD
group by salesman_id, annee
ORDER BY ANNEE;

CREATE OR REPLACE VIEW ANNE_MEILLEUR_VENTES_DE_VENDEUR AS
select 
    annee,
    MAX(TOTAL_VENTES_CETTE_ANNEE) AS "TOTAL_MEILLEURES_VENTES_DU_MEILLEUR_VENDEUR"
from (SELECT SALESMAN_ID, annee, sum(total_commande) as "TOTAL_VENTES_CETTE_ANNEE"
FROM ORDER_DATE_ANNEE OD
group by salesman_id, annee
    having salesman_id is not null
ORDER BY ANNEE) TT
group by annee;

-- LES MATCH ENTRE LE MEILLEUR VENDEURE T LES MEILLEUR VENTES DE LA PREMIRE ANEE
-- ANNEE, TOTAL, ID, ANNEE
--CREATE OR REPLACE VIEW MEILLEURES_VENTES_PAR_ANNEE_ET_SON_MEILLEUR_VENDEUR AS

CREATE OR REPLACE VIEW COMMANDES_INFO AS
SELECT  -- AM.ANNEE, AM.TOTAL_MEILLEURES_VENTES_DU_MEILLEUR_VENDEUR, MV.SALESMAN_ID
    AM.ANNEE, AM.TOTAL_MEILLEURES_VENTES_DU_MEILLEUR_VENDEUR, MV.SALESMAN_ID,
    MVA.MOYENNE_VENTES_CETTE_ANNEE
FROM ANNE_MEILLEUR_VENTES_DE_VENDEUR AM
JOIN MEILLEURE_VENTES_VENDEURS_ANNEE MV 
ON MV.TOTAL_VENTES_CETTE_ANNEE = AM.TOTAL_MEILLEURES_VENTES_DU_MEILLEUR_VENDEUR
JOIN MOYENNE_VENTES_ANNEE MVA ON MVA.ANNEE = AM.ANNEE;


