DROP TABLE Client;
DROP TABLE ADRESSE;

CREATE TABLE ADRESSE
(
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    RUE VARCHAR2(50),
    VILLE VARCHAR2(50),
    CODEPOSTAL VARCHAR2(50),
    PAYS VARCHAR2(50)
);

CREATE TABLE Client
(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nom VARCHAR2(50),
    prenom VARCHAR2(50),
    email VARCHAR2(50),
    genre VARCHAR2(50) CHECK(genre = 'HOMME' OR genre = 'FEMME' OR genre = 'AUTRE' ),
    id_adresse NUMBER REFERENCES ADRESSE(id),
    date_naissance Date
);

CREATE TABLE Commande
(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
);

select * from CLIENT;
-- CREATE SEQUENCE employee_seq
--     START WITH 1
--     INCREMENT BY 1;